### ISSUE TITLE
exactly correct Orthogroups aren't calculated correctly

### ISSUE THREAD

**Issue by JLSteenwyk** [davidemms/Open_Orthobench#2]
Hi,

Thanks for another great piece of software from the group!

I noticed that the way exactly correct orthogroups (OG) doesn't account certain instances.

Specifically, if an inferred orthogroup (iOG) has a subset of genes in a reference OG (rOG), then the `benchmark.py` script will count this as an exactly correct OG. This occurs because exactly correct OGs are only counted if false positives and false negatives are not detected, but the number of true positives is too few (see [line 243](https://github.com/davidemms/Open_Orthobench/blob/872d6f30592ab5ff837224db16a514b3f2bb916a/BENCHMARKS/benchmark.py#L243C36-L244C1)).

Cheers,

Jacob

**Comment by lauriebelch** [comment]
Hi Jacob,

Do you have a simple example of when this would occur? I'm struggling to get my head around it

Although I think we can definitely change the code to compare the two 'sets', to make it more robust

Laurie

**Comment by JLSteenwyk** [comment]
Hi Laurie,

My sincere apologies. I believe I made an error.

Thank you for your response and my apologies for this!
